AWSTemplateFormatVersion: '2010-09-09'
Description: Creating the EC2 instances for region 2


Parameters:
  UsVpcId:
    Type: String
    Description: The VPC ID for US 
  PublicSubnet1Id:
    Type: String
    Description: The ID for the first public subnet
  PublicSubnet2Id:
    Type: String
    Description: The ID for the second public subnet
  PrivateSubnet1Id:
    Type: String
    Description: The ID for the first private subnet
  PrivateSubnet2Id:
    Type: String
    Description: The ID for the second private subnet
  UsEC2TestSgId:
    Type: String
    Description: The ID for the security group

Resources:

  MyEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - ! ec2-allow-ssm-cloudwatch-role
      InstanceProfileName: !Sub 'ec2-allow-ssm-cloudwatch-role-${AWS::Region}'

  InstancePublic1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08a6efd148b1f7504
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet1Id
      SecurityGroupIds:
        - !Ref UsEC2TestSgId
      IamInstanceProfile: !Ref MyEc2InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
      Tags:
      - Key: Name
        Value: us-Public-Test-Instance-AZ1

  InstancePublic2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08a6efd148b1f7504
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet2Id
      SecurityGroupIds:
        - !Ref UsEC2TestSgId
      IamInstanceProfile: !Ref MyEc2InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
      Tags:
      - Key: Name
        Value: us-Public-Test-Instance-AZ2
  
  InstancePrivate1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08a6efd148b1f7504
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet1Id
      SecurityGroupIds:
        - !Ref UsEC2TestSgId
      IamInstanceProfile: !Ref MyEc2InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
      Tags:
      - Key: Name
        Value: us-Private-Test-Instance-AZ1

  InstancePrivate2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08a6efd148b1f7504
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref UsEC2TestSgId
      IamInstanceProfile: !Ref MyEc2InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
      Tags:
      - Key: Name
        Value: us-Private-Test-Instance-AZ2
